language: csharp
sudo: required
mono: none
dist: xenial
dotnet: 2.2

branches:
  except:
    - 1.0
    - 2.0
    - 2.1
    - dse_3.1
    
matrix:
  include:
    - env: TARGETF=netcoreapp2.1
    - env: TARGETF=netcoreapp2.0

script:
  - dotnet restore src
  - dotnet test src/Cassandra.Tests/Cassandra.Tests.csproj -c Release -f $TARGETF